### ISSUE TITLE
Implement system event notifications for QuickPass on all platforms

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#51]
### Description:
Implement system event notifications for system events which are relevant to clearing _QuickPass_-related data from RAM (like user logoff, user switching, idle state ...) on all platforms:

- [x] Windows (Implemented in #48)
- [x] Linux (Implemented in #63)
- [x] MacOS (Implemented in #62)

This should be done by creating an implementation for the `ISystemEventNotifier` interface for each platform.

**Comment by josegomez** [comment]
@alexhauser  so Computer Shutdown and Session Log Off , why do we care? Wouldn't the application halt anyways when that happens? Why bother registering these events? Is just to be safe?

**Comment by josegomez** [comment]
I'm starting to look at this for MacOS

**Comment by alexhauser** [comment]
> @alexhauser so Computer Shutdown and Session Log Off , why do we care? Wouldn't the application halt anyways when that happens? Why bother registering these events? Is just to be safe?

Yes. Under normal circumstances, if the app (or rather the garbage collector) has enough time to wind everything down properly, it shouldn't matter. But how to be sure that this is always the case?

So I just added it because I was implementing the whole window messaging subsystem anyway, and it was easy to add those as well.

**Comment by josegomez** [comment]
Starting the Linux one @alexhauser  ... this one bodes to be a nightmare not sure there's is a standard way of doing any of these across linux... We'll see

**Comment by alexhauser** [comment]
Cool, looking forward to seeing your findings @josegomez!

**Comment by josegomez** [comment]
Implemented for Linux on #63
