### ISSUE TITLE
Implement notification icon for all platforms

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#52]
### Description:
Implement taskbar/panel/dock notification icon on all platforms. The goal is to have the app running "in the background" while having an easy way to activate it.

- [x] Windows (Implemented in #48)
- [x] Linux (Implemented in #58 )
- [x] MacOS (Implemented in #55)

This should be done by creating an implementation for the `INotifyIcon` interface for each platform.

**Comment by josegomez** [comment]
I'll take this for the Mac next. @alexhauser

**Comment by alexhauser** [comment]
Cool, can't wait to see what you'll come up with @josegomez!

**Comment by josegomez** [comment]
@alexhauser Working on Linux version... 
I have no earthly idea how well it will work particularly since there's GNOME, and KDE and about a thousand other Desktop Environments.
I'm writing this to work on Ubuntu and everything else if it works.. well... great LoL

Too many flavors of Linux

**Comment by josegomez** [comment]
Implemented Linux in #58

**Comment by josegomez** [comment]
Merged , done with #58
